<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>COMMIT_EDITMSG</string>
		<string>MERGE_MSG</string>
		<string>TAG_EDITMSG</string>
	</array>
	<key>name</key>
	<string>Git Commit Message (tmLanguage)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.too-long</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?:.{1,72})(.*)</string>
					<key>name</key>
					<string>text.git-commit-msg.body</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.branch-name</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#\sOn branch (.*)</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.status.ahead</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.status.behind</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.branch-name.remote</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#\sYour branch is (?:(ahead) of|(behind)) '(.*)' by (\d+) commit(?:s?(?:\.|, and can be fast-forwarded\.))</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.status.up-to-date</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.branch-name.remote</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#\sYour branch is (up-to-date) with '(.*)'\.</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.branch-name.remote</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.status.diverged</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#\sYour branch and '(.*)' have (diverged),</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^# and have (\d+) and (\d+) different commits each, respectively\.</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.author</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.name</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.email</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#\s(Author:)\s+(.*)\s&lt;([^&gt;]+)&gt;</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.date</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.date</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#\s(Date:)\s+(.*)</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^#\s(Changes to be committed:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.heading</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^#\s*$</string>
					<key>name</key>
					<string>text.git-commit-msg.committed comment.line.number-sign</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.new-file</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.inserted</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(new file:)\s+(.*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.modified</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.changed</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(modified:)\s+(.*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.renamed</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.changed</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.operator</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>markup.inserted</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(renamed:)\s+(.*?)(?:\s(-&gt;)\s)(.*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.deleted</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.deleted</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(deleted:)\s+(.*)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^#\s(Changes not staged for commit:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.heading</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^#\s*$</string>
					<key>name</key>
					<string>text.git-commit-msg.unstaged comment.line.number-sign</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.new-file</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.inserted</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(new file:)\s+(.*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.modified</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.changed</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(modified:)\s+(.*)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.other.deleted</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.deleted</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(deleted:)\s+(.*)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^# (Untracked files:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.heading</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^#\s*$</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>markup.list.unnumbered.untracked</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(\S.*)$</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^# (Conflicts:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.heading</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^#\s*$</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>markup.list.unnumbered.resolved-conflict</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(\S.*)$</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^# If this is not correct, please remove the file</string>
					<key>end</key>
					<string>^#\s+and try again\.$</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.unquoted.merge-head</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^#\s+(\S.*)$</string>
							<key>name</key>
							<string>comment.line.number-sign</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^#\s+------------------------ &gt;8 ------------------------</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign meta.diff.marker</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=ThisNeverEnds)1234567890123</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>^#.*</string>
							<key>name</key>
							<string>comment.line.number-sign</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>^(?!#)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>comment.line.number-sign</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.diff</string>
							<key>end</key>
							<string>(?=ThisNeverEnds)1234567890123</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.diff</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(^#.*$)</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(^\s*$)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:.{1,50})(.{0,22})(.*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>text.git-commit-msg.summary</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.slightly-too-long</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.too-long</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=ThisNeverEnds)1234567890123</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#second-line</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>second-line</key>
		<dict>
			<key>begin</key>
			<string>^(\s*$|(^(?!#)\s*\S+.*))</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.should-be-blank</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=ThisNeverEnds)1234567890123</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#body</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.git-commit-msg</string>
	<key>uuid</key>
	<string>69AB7563-44F7-446C-B3A9-7CFEC8D50B1C</string>
</dict>
</plist>
