<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>git-rebase-todo</string>
	</array>
	<key>name</key>
	<string>Git Rebase Todo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#main</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>text.git-rebase-todo.command-description</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#(\s+[^,]+,\s+[a-z]+\s+=.*)$</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.operator</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#\sRebase ([a-f0-9]+)(..)([a-f0-9]+) onto ([a-f0-9]+) \((\d+) commands\)</string>
					<key>name</key>
					<string>comment.line.number-sign text.git-rebase-todo.description</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^#.*$</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted text.git-rebase-todo.summary</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(p(?:ick)?)\s+([a-f0-9]{4,40})\s+(.*)$</string>
					<key>name</key>
					<string>text.git-rebase-todo.command.pick</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted text.git-rebase-todo.summary</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(e(?:dit)?)\s+([a-f0-9]{4,40})\s+(.*)$</string>
					<key>name</key>
					<string>text.git-rebase-todo.command.edit</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted text.git-rebase-todo.summary</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(r(?:eword)?)\s+([a-f0-9]{4,40})\s+(.*)$</string>
					<key>name</key>
					<string>text.git-rebase-todo.command.reword</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted text.git-rebase-todo.summary</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(f(?:ixup)?)\s+([a-f0-9]{4,40})\s+(.*)$</string>
					<key>name</key>
					<string>text.git-rebase-todo.command.fixup</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted text.git-rebase-todo.summary</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(s(?:quash)?)\s+([a-f0-9]{4,40})\s+(.*)$</string>
					<key>name</key>
					<string>text.git-rebase-todo.command.squash</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric text.git-rebase-todo.sha</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted text.git-rebase-todo.summary</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(d(?:rop)?)\s+([a-f0-9]{4,40})\s+(.*)$</string>
					<key>name</key>
					<string>text.git-rebase-todo.command.drop</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(x|(?:exec))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>text.git-rebase-todo.command.exec keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.shell</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^.*$</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.git-rebase-todo</string>
	<key>uuid</key>
	<string>887E9394-E31C-4DC5-B9BE-8BA9F591C6E1</string>
</dict>
</plist>
